package com.app.fileserver.dao;

import com.app.fileserver.entity.FileInfo;

public interface FileInfoMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    int insertSelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    int updateByPrimaryKeySelective(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    int updateByPrimaryKey(FileInfo record);

    /**
     * 查找文件
     */
    FileInfo getFileByUUID(String uuid);
}
