package com.app.fileserver.entity;

public class FileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.id
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.path
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.type
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.name
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.suffix
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.size
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private Double size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.uuid
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.id
     *
     * @return the value of fileinfo.id
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.id
     *
     * @param id the value for fileinfo.id
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.path
     *
     * @return the value of fileinfo.path
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.path
     *
     * @param path the value for fileinfo.path
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.type
     *
     * @return the value of fileinfo.type
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.type
     *
     * @param type the value for fileinfo.type
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.name
     *
     * @return the value of fileinfo.name
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.name
     *
     * @param name the value for fileinfo.name
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.suffix
     *
     * @return the value of fileinfo.suffix
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.suffix
     *
     * @param suffix the value for fileinfo.suffix
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.size
     *
     * @return the value of fileinfo.size
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public Double getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.size
     *
     * @param size the value for fileinfo.size
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setSize(Double size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.uuid
     *
     * @return the value of fileinfo.uuid
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.uuid
     *
     * @param uuid the value for fileinfo.uuid
     *
     * @mbggenerated Sat Aug 31 22:19:12 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
}